server:
    port: 8082

info:
    env: LOCAL

logging:
    config: config/logback-local.xml


spring:
    datasource:
        url: jdbc:h2:mem:testData;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
        username: sa
        password:
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
    h2:
        console:
            enabled: true

liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql
    enabled: true
    url: jdbc:h2:mem:testData;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    user: sa
    password:

authentication:
    jwt:
      expire: 864000000
      secret: secret
      token-prefix: Bearer
      header: Authorization